module.exports = {
  signedup: "You signed up successfully",
  duplicateEmail: "This account with this email already exist",
  logout: "You loged out successfully",
  loged: "You aleady Logged Out",
  login: "Please Login",
  duplicateUsername: "This Username is in use",
  emailConfirmation: "A verification email has been sent to ",
  accountVerified: "The account has been verified. Please log in.",
  userVerification: "This user has already been verified.",
  emailAssociate: "we are unable to find a user with that email!",
  thisAccountVerified: "This account has  already been verified.Please log In",
  noEmailAssociate: "no account associated to this email",
  passwordReset: "The link to reset password sent succesfully to your email!",
  passwordMatch: "password don't match",
  passwordUpdated: "password updated succesfully!",
  resend: "confirmation email resend succesfully!",
  onCreate: "Request submitted",
  onUpdate: "Request updated!",
  onDelete: "Request deleted",
  emailExist: "User already exists with that email",
  missingFields: "please add email or password",
  authError: "Invalid Email or password",
};
